apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expensy
spec:
  replicas: 2
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: 686699774218.dkr.ecr.eu-central-1.amazonaws.com/expensy-frontend:1e64885973a92f59b2428b28894ca0da0ac8aa88
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet: { path: /, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 3000 }
            initialDelaySeconds: 20
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expensy
spec:
  selector: { app: frontend }
  ports:
    - port: 3000
      targetPort: 3000
